version: "3.8"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.8.0
    container_name: workflow-nginx-proxy
    restart: always
    ports:
    - "10.0.10.79:80:80"
    - "10.0.10.79:443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
    - ENABLE_IPV6=true


  nexus3:
    image: sonatype/nexus3:3.30.1
    restart: always
    container_name: workflow-nexus3
    environment:
    - VIRTUAL_HOST=nexus.nova.ccg
    - VIRTUAL_PORT=8081
    expose:
    - "8081"
    ports:
    - "10.0.10.79:5000:8082"
    - "10.0.10.79:8083:8083"
    volumes:
    - /data/inspur_disk01/userdir/docker/nexus/nexus-data:/nexus-data
    depends_on:
    - nginx-proxy

