apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vol
  namespace: userName
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: data-vol
  resources:
    requests:
      storage: 1G
  selector: 
    matchLabels:
      node: nova
      disk: inspur-disk01
      user: userName
      type: nfs
