apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: user-<profileName>   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: /user/userid@email.com   # replace with the email of the user

  resourceQuotaSpec:    # resource quota can be set optionally
    hard: #mid
      cpu: "24.5"
      memory: 128Gi
      requests.nvidia.com/gpu: "2"
      persistentvolumeclaims: "4"
      requests.storage: "500Gi"
