apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  files:
  - ./spawner_ui_config.yaml
  name: jupyter-web-app-config
images:
- name: gcr.io/kubeflow-images-public/admission-webhook
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.admission-webhook
  newTag: vmaster-ge5452b6f
- name: gcr.io/kubeflow-images-public/centraldashboard
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.centraldashboard
  newTag: vmaster-g8097cfeb
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.jupyter-web-app
  newTag: vmaster-ge4456300
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.notebook-controller
  newTag: vmaster-g6eb007d0
- name: gcr.io/kubeflow-images-public/kfam
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.kfam
  newTag: vmaster-g9f3bfd00
- name: gcr.io/kubeflow-images-public/profile-controller
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.profile-controller
  newTag: vmaster-ga49f658f
- name: gcr.io/kubeflow-images-public/pytorch-operator
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.pytorch-operator
  newTag: vmaster-g518f9c76
- name: gcr.io/kubeflow-images-public/tf_operator
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.tf_operator
  newTag: vmaster-gda226016
- name: mxjob/mxnet-operator
  newName: docker.io/txmao/kf12-mxjob.mxnet-operator
  newTag: v1.0.0-20200625
- name: mpioperator/mpi-operator
  newName: docker.io/txmao/kf12-mpioperator.mpi-operator
  newTag: txmao-v1.0.5
- name: docker.io/kubeflowkatib/katib-controller
  newName: docker.io/txmao/kf12-docker.io.kubeflowkatib.katib-controller
  newTag: v1beta1-a96ff59
- name: docker.io/kubeflowkatib/katib-ui
  newName: docker.io/txmao/kf12-docker.io.kubeflowkatib.katib-ui
  newTag: v1beta1-a96ff59
- name: docker.io/kubeflowkatib/katib-db-manager
  newName: docker.io/txmao/kf12-docker.io.kubeflowkatib.katib-db-manager
  newTag: v1beta1-a96ff59
- name: mysql
  newName: docker.io/txmao/kf12-mysql
  newTag: "8"
- name: gcr.io/ml-pipeline/mysql
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.mysql
  newTag: "5.6"
- name: gcr.io/ml-pipeline/api-server
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.api-server
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/persistenceagent
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.persistenceagent
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.scheduledworkflow
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/frontend
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.frontend
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.viewer-crd-controller
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/visualization-server
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.visualization-server
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/metadata-writer
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.metadata-writer
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/cache-deployer
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.cache-deployer
  newTag: 1.0.4
- name: gcr.io/ml-pipeline/cache-server
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.cache-server
  newTag: 1.0.4
- name: argoproj/argoui
  newName: docker.io/txmao/kf12-argoproj.argoui
  newTag: v2.3.0
- name: argoproj/workflow-controller
  newName: docker.io/txmao/kf12-argoproj.workflow-controller
  newTag: v2.3.0
- name: mysql
  newName: docker.io/txmao/kf12-mysql
  newTag: 8.0.3
- name: gcr.io/kubeflow-images-public/metadata
  newName: docker.io/txmao/kf12-gcr.io.kubeflow-images-public.metadata
  newTag: v0.1.11
- name: gcr.io/tfx-oss-public/ml_metadata_store_server
  newName: docker.io/txmao/kf12-gcr.io.tfx-oss-public.ml_metadata_store_server
  newTag: v0.21.1
- name: gcr.io/ml-pipeline/envoy
  newName: docker.io/txmao/kf12-gcr.io.ml-pipeline.envoy
  newTag: metadata-grpc
- name: mysql
  newName: docker.io/txmao/kf12-mysql
  newTag: 8.0.3
- name: quay.io/jetstack/cert-manager-controller
  newName: docker.io/txmao/kf12-quay.io.jetstack.cert-manager-controller
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-webhook
  newName: docker.io/txmao/kf12-quay.io.jetstack.cert-manager-webhook
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-cainjector
  newName: docker.io/txmao/kf12-quay.io.jetstack.cert-manager-cainjector
  newTag: v0.11.0
- name: gcr.io/spark-operator/spark-operator
  newName: docker.io/txmao/kf12-gcr.io.spark-operator.spark-operator
  newTag: v1beta2-1.1.0-2.4.5
- name: quay.io/dexidp/dex
  newName: docker.io/txmao/kf12-quay.io.dexidp.dex
  newTag: v2.22.0
- name: docker.io/prom/prometheus
  newName: docker.io/txmao/kf12-docker.io.prom.prometheus
  newTag: v2.8.0
- name: gcr.io/istio-release/citadel
  newName: docker.io/txmao/kf12-gcr.io.istio-release.citadel
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/galley
  newName: docker.io/txmao/kf12-gcr.io.istio-release.galley
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/kubectl
  newName: docker.io/txmao/kf12-gcr.io.istio-release.kubectl
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/mixer
  newName: docker.io/txmao/kf12-gcr.io.istio-release.mixer
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/node-agent-k8s
  newName: docker.io/txmao/kf12-gcr.io.istio-release.node-agent-k8s
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/pilot
  newName: docker.io/txmao/kf12-gcr.io.istio-release.pilot
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/proxyv2
  newName: docker.io/txmao/kf12-gcr.io.istio-release.proxyv2
  newTag: release-1.3-latest-daily
- name: gcr.io/istio-release/sidecar_injector
  newName: docker.io/txmao/kf12-gcr.io.istio-release.sidecar_injector
  newTag: release-1.3-latest-daily
- name: gcr.io/google_containers/spartakus-amd64
  newName: docker.io/txmao/kf12-gcr.io.google_containers.spartakus-amd64
  newTag: v1.1.0
- name: docker.io/istio/kubectl
  newName: docker.io/txmao/kf12-docker.io.istio.kubectl
  newTag: 1.1.6
- name: docker.io/istio/galley
  newName: docker.io/txmao/kf12-docker.io.istio.galley
  newTag: 1.1.6
- name: docker.io/istio/proxyv2
  newName: docker.io/txmao/kf12-docker.io.istio.proxyv2
  newTag: 1.1.6
- name: grafana/grafana
  newName: docker.io/txmao/kf12-grafana.grafana
  newTag: 6.0.2
- name: docker.io/kiali/kiali
  newName: docker.io/txmao/kf12-docker.io.kiali.kiali
  newTag: v0.16
- name: docker.io/istio/mixer
  newName: docker.io/txmao/kf12-docker.io.istio.mixer
  newTag: 1.1.6
- name: docker.io/istio/pilot
  newName: docker.io/txmao/kf12-docker.io.istio.pilot
  newTag: 1.1.6
- name: docker.io/prom/prometheus
  newName: docker.io/txmao/kf12-docker.io.prom.prometheus
  newTag: v2.3.1
- name: docker.io/istio/citadel
  newName: docker.io/txmao/kf12-docker.io.istio.citadel
  newTag: 1.1.6
- name: docker.io/istio/sidecar_injector
  newName: docker.io/txmao/kf12-docker.io.istio.sidecar_injector
  newTag: 1.1.6
- name: docker.io/jaegertracing/all-in-one
  newName: docker.io/txmao/kf12-docker.io.jaegertracing.all-in-one
  newTag: "1.9"
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: docker.io/txmao/kf12-gcr.io.arrikto.kubeflow.oidc-authservice
  newTag: 28c59ef
kind: Kustomization
resources:
- ../../.cache/manifests/manifests-1.2-branch/stacks/kubernetes
