FROM gcr.io/kubeflow-images-public/tensorflow-1.15.2-notebook-gpu:1.0.0
LABEL MAINTAINER="TX Mao <mtianxiang@gmail.com>"

USER root
COPY ./pip.conf /usr/pip.conf

# Configure container startup
EXPOSE 8888
USER jovyan
ENTRYPOINT ["tini", "--"]
CMD ["sh","-c", "jupyter notebook --notebook-dir=/home/${NB_USER} --ip=0.0.0.0 --no-browser --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
