apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  envs:
  - ./params.env
  name: oidc-authservice-parameters
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: docker.io/txmao/kf12-gcr.io.arrikto.kubeflow.oidc-authservice
  newTag: 28c59ef
kind: Kustomization
resources:
- ../../.cache/manifests/manifests-1.2-branch/istio/oidc-authservice/overlays/application
