name: build_docker_images

on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      -
        name: image for pytorch 1.7.1
        uses: docker/build-push-action@v2
        with:
          context: images
          file: images/Dockerfile.pytorch.gpu
          push: true
          tags: txmao/kf-jupyter-pytorch-1.7.1-gpu:${{ steps.vars.outputs.tag }}

      -
        name: image for tf2.1.0
        uses: docker/build-push-action@v2
        with:
          context: images
          file: images/Dockerfile.tf210.gpu
          push: true
          tags: txmao/kf-jupyter-tensorflow-2.1.0-gpu:${{ steps.vars.outputs.tag }}

      -
        name: image for tf1.15.2
        uses: docker/build-push-action@v2
        with:
          context: images
          file: images/Dockerfile.tf115.gpu
          push: true
          tags: txmao/kf-jupyter-tensorflow-1.15.2-gpu:${{ steps.vars.outputs.tag }}
