name: copy_docker_image

on:  [push]
# push:
#   branches:
#     - 'master'

jobs:
  setmatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: create tasks
        id: set-matrix
        run: |
          output=$(cat tools/replace_images.yaml)
          echo "::set-output name=matrix::$output"

  docker:
    runs-on: ubuntu-latest
    needs: setmatrix
    strategy:
      matrix: ${{ fromJson(needs.setmatrix.outputs.matrix) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # copy multiplatform image from dockerhub to quay and ghcr
        name: Push Image to dockerhub registrie
        uses: akhilerm/tag-push-action@v1.0.0
        with:
          src: mysql:latest
          dst: docker.io/txmao/testmysql:test
#         src: ${{ matrix.src }}
#         dst: ${{ matrix.dst }}
